services:
  - type: web
    name: moviesite
    env: docker
    region: oregon
    plan: free
    buildCommand: "./gradlew clean bootJar -x test"
    startCommand: "java -jar build/libs/*.jar"

databases:
  - name: moviedb
    databaseName: moviedb
    user: movieuser
    plan: free

